build:
  tests:
    override:
      - command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'some-file'
          format: 'clover'
checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - vendor/*

before_commands:
  - "composer install --prefer-source"