preset: recommended

risky: false

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow
  - laravel

disabled:
  - align_double_arrow
  - short_array_syntax

finder:
  exclude:
    - "tests"