ignore:
  - "tests"
  - "migrations"
  - "container"
  - "storage"
  - "vendor"
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null